# tf.constant

In [26]:
import tensorflow as tf

In [3]:
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')

In [4]:
print(x)

Tensor("add:0", shape=(), dtype=int32)


In [5]:
sess = tf.Session()

writer = tf.summary.FileWriter('./temp', sess.graph)
print("a+b=%r" % sess.run(x))

writer.close()

a+b=5


In [6]:
input_tensor = [[0,1],[2,3],[4,5]]

# [[0,0,0],[0,0,0]]
op_zeros = tf.zeros([2,3], tf.int32)

# [[0,0],[0,0],[0,0]]
op_zeros_like = tf.zeros_like(input_tensor)

# [[1,1,1],[1,1,1]]
op_ones = tf.ones([2,3], tf.int32)

# [[1,1],[1,1],[1,1]]
op_ones_like = tf.ones_like(input_tensor)

# [[8,8,8],[8,8,8]]
op_ones_fill = tf.ones([2,3], 8)

In [7]:
op_zeros, op_zeros_like, op_ones, op_ones_like, op_ones_fill = \
    sess.run([op_zeros, op_zeros_like, op_ones, op_ones_like, op_ones_fill])

In [8]:
print("op_zeros=\n%r" % op_zeros)

op_zeros=
array([[0, 0, 0],
       [0, 0, 0]])


In [9]:
print("op_zeros_like=\n%r" % op_zeros_like)

op_zeros_like=
array([[0, 0],
       [0, 0],
       [0, 0]])


In [10]:
print("op_ones=\n%r" % op_ones)

op_ones=
array([[1, 1, 1],
       [1, 1, 1]])


In [11]:
print("op_ones_like=\n%r" % op_ones_like)

op_ones_like=
array([[1, 1],
       [1, 1],
       [1, 1]])


In [12]:
print("op_ones_fill=\n%r" % op_ones_fill)

op_ones_fill=
array([[ 1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j,  1.+0.j]], dtype=complex64)


In [17]:
op_linspace = tf.linspace(10.0, 13.0, 4, name="linspace")

start = 3
limit = 18
delta = 3
op_range_limit18_start3_delta3 = tf.range(start, limit, delta)

limit = 5
op_range_limit5_default = tf.range(limit)

op_linspace,op_range_limit18_start3_delta3,op_range_limit5_default = \
    sess.run([op_linspace,op_range_limit18_start3_delta3,op_range_limit5_default])
    
print("op_linspace=\t\t\t%r" % op_linspace)
print("op_range_limit18_start3_delta3=\t%r" % op_range_limit18_start3_delta3)
print("op_range_limit5_default=\t%r" % op_range_limit5_default)

op_linspace=			array([ 10.,  11.,  12.,  13.], dtype=float32)
op_range_limit18_start3_delta3=	array([ 3,  6,  9, 12, 15])
op_range_limit5_default=	array([0, 1, 2, 3, 4])


In [23]:
# Note that unlike NumPy or Python sequences, TensorFlow sequences are not iterable.
import numpy as np
for _ in np.linspace(0, 10, 4):
    print(_)

0.0
3.33333333333
6.66666666667
10.0


In [28]:
for _ in tf.linspace(0.0, 10, 4):
    print(_)

TypeError: 'Tensor' object is not iterable.

In [ ]:
# 